version: '3.8'

services:
  app:
    build: .
    container_name: restaurant-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - restaurant-network

  nginx:
    image: nginx:alpine
    container_name: restaurant-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - restaurant-network

  postgres:
    image: postgres:13
    container_name: restaurant-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: restaurant_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - restaurant-network

  redis:
    image: redis:alpine
    container_name: restaurant-redis
    restart: unless-stopped
    networks:
      - restaurant-network

networks:
  restaurant-network:
    driver: bridge

volumes:
  postgres_data: